
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import math
global operator
global text
global text2,text3,op2
operator=""
text=""
text2=""
op2=""
text3=""

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 429)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_clear = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear.setGeometry(QtCore.QRect(270, 220, 141, 23))
        self.pushButton_clear.setStyleSheet("QPushButton{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"    border-color: rgb(208, 69, 104);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 0, 127)\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(9, 9, 401, 181))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(0, 0, 0); color:rgb(255, 255, 255);")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.pushButton_del = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_del.setGeometry(QtCore.QRect(10, 220, 91, 23))
        self.pushButton_del.setStyleSheet("QPushButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"    font: 9pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"    border-color: rgb(208, 69, 104);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(255, 0, 127)\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_del.setObjectName("pushButton_del")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 376, 401, 31))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_dot = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_dot.setStyleSheet("QPushButton{\n"
"    \n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_dot.setObjectName("pushButton_dot")
        self.horizontalLayout_2.addWidget(self.pushButton_dot)
        self.pushButton_zero = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_zero.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_zero.setObjectName("pushButton_zero")
        self.horizontalLayout_2.addWidget(self.pushButton_zero)
        self.pushButton_answer = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_answer.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color:rgb(255, 2, 2);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color:rgb(255, 2, 2);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_answer.setObjectName("pushButton_answer")
        self.horizontalLayout_2.addWidget(self.pushButton_answer)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 250, 401, 31))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_pluse = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_pluse.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_pluse.setObjectName("pushButton_pluse")
        self.horizontalLayout.addWidget(self.pushButton_pluse)
        self.pushButton_devide = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_devide.setStyleSheet("QPushButton{\n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_devide.setObjectName("pushButton_devide")
        self.horizontalLayout.addWidget(self.pushButton_devide)
        self.pushButton_minus = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_minus.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.horizontalLayout.addWidget(self.pushButton_minus)
        self.pushButton_multiple = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_multiple.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_multiple.setObjectName("pushButton_multiple")
        self.horizontalLayout.addWidget(self.pushButton_multiple)
        self.pushButton_power = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_power.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(244, 255, 34);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(244, 255, 34);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_power.setObjectName("pushButton_power")
        self.horizontalLayout.addWidget(self.pushButton_power)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(330, 280, 81, 91))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_sin = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_sin.setStyleSheet("QPushButton{\n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 217, 217);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color:rgb(0, 217, 217);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_sin.setObjectName("pushButton_sin")
        self.verticalLayout.addWidget(self.pushButton_sin)
        self.pushButton_cos = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_cos.setStyleSheet("QPushButton{\n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 217, 217);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color:rgb(0, 217, 217);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_cos.setObjectName("pushButton_cos")
        self.verticalLayout.addWidget(self.pushButton_cos)
        self.pushButton_tan = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_tan.setStyleSheet("QPushButton{\n"
"    font: 75 13pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 217, 217);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color:rgb(0, 217, 217);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_tan.setObjectName("pushButton_tan")
        self.verticalLayout.addWidget(self.pushButton_tan)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 280, 311, 91))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 1, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 2, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 2, 1, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:8px;\n"
"border-width:2px;\n"
"border-color: rgb(0, 197, 0);\n"
"border-style:outset;\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(0, 197, 0);\n"
"}\n"
"\n"
"\n"
"")
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 420, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.method_1)
        self.pushButton_2.clicked.connect(self.method_2)
        self.pushButton_3.clicked.connect(self.method_3)
        self.pushButton_4.clicked.connect(self.method_4)
        self.pushButton_5.clicked.connect(self.method_5)
        self.pushButton_6.clicked.connect(self.method_6)
        self.pushButton_7.clicked.connect(self.method_7)
        self.pushButton_8.clicked.connect(self.method_8)
        self.pushButton_9.clicked.connect(self.method_9)
        self.pushButton_zero.clicked.connect(self.method_zero)
        self.pushButton_dot.clicked.connect(self.method_dot)
        self.pushButton_answer.clicked.connect(self.method_answer)
        self.pushButton_pluse.clicked.connect(self.method_plus)
        self.pushButton_minus.clicked.connect(self.method_minus)
        self.pushButton_multiple.clicked.connect(self.method_mutiple)
        self.pushButton_devide.clicked.connect(self.method_devide)
        self.pushButton_power.clicked.connect(self.method_power)
        self.pushButton_sin.clicked.connect(self.method_sin)
        self.pushButton_cos.clicked.connect(self.method_cos)
        self.pushButton_tan.clicked.connect(self.method_tan)
        self.pushButton_clear.clicked.connect(self.method_clear)
        self.pushButton_del.clicked.connect(self.method_delete)

    def method_1(self):
        text=self.label.text()
        self.label.setText(text+"1")
    def method_2(self):
        text=self.label.text()
        self.label.setText(text+"2")
    def method_3(self):
        text=self.label.text()
        self.label.setText(text+"3")
    def method_4(self):
        text=self.label.text()
        self.label.setText(text+"4")
    def method_5(self):
        text=self.label.text()
        self.label.setText(text+"5")
    def method_6(self):
        text=self.label.text()
        self.label.setText(text+"6")
    def method_7(self):
        text=self.label.text()
        self.label.setText(text+"7")
    def method_8(self):
        text=self.label.text()
        self.label.setText(text+"8")
    def method_9(self):
        text=self.label.text()
        self.label.setText(text+"9")
    def method_zero(self):
        text=self.label.text()
        self.label.setText(text+"0")
    def method_clear(self):
        self.label.setText("")
        operator=""
        text=""
        text2=""
        text3=""
        op2=""
    def method_delete(self):
        text=self.label.text()
        self.label.setText(text[:len(text)-1])

    def method_dot(self):
        text=self.label.text()
        self.label.setText(text+".")

    def method_plus(self):
        global operator
        global  text
        if operator !="":
            self.method_answer()
        global  text
        text=self.label.text()
        text=float(text)
        operator="+"
        self.label.setText("")
            
            
        
    def method_minus(self):
        global operator
        if operator !="":
            self.method_answer()
        global  text
        text=self.label.text()
        text=float(text)
        operator="-"
        self.label.setText("")

    def method_mutiple(self):
        global operator
        if operator !="":
            self.method_answer()
        global  text
        text=self.label.text()
        text=float(text)
        operator="*"
        self.label.setText("")

    def method_devide(self):
        global operator
        if operator !="":
            self.method_answer()
        global  text
        text=self.label.text()
        text=float(text)
        operator="/"
        self.label.setText("")
    
    def method_power(self):
        global operator
        if operator !="":
            self.method_answer()
        global  text
        text=self.label.text()
        text=float(text)
        operator="**"
        self.label.setText("")
    
    def method_sin(self):
        global operator
        if operator !="":
            global op2
            global  text
            global text3
            text3=text
            op2=operator
            self.label.setText("")
            text=""
            operator=""
            self.method_sin()

        else:
            self.label.setText("")
            operator="sin"

    def method_cos(self):
        global operator
        if operator !="":
            global op2
            global  text
            global text3
            text3=text
            op2=operator
            self.label.setText("")
            text=""
            operator=""
            self.method_cos()

        else:
            self.label.setText("")
            operator="cos"

    def method_tan(self):
        global operator
        if operator !="":
            global op2
            global  text
            global text3
            text3=text
            op2=operator
            self.label.setText("")
            text=""
            operator=""
            self.method_tan()

        else:
            self.label.setText("")
            operator="tan"


    def method_answer(self):
        global text2,text3,text,operator,op2,c
        c=0
        if operator=="+":
            text2=self.label.text()
            text2=float(text2)
            text=float(text)
            self.label.setText("")
            ans=text+text2
            text=ans
            self.label.setText(str(text))
            operator=""

        if operator=="-":
            text2=self.label.text()
            text2=float(text2)
            self.label.setText("")
            text=text-text2
            self.label.setText(str(text))
            operator=""
        
        if operator=="*":
            text2=self.label.text()
            text2=float(text2)
            self.label.setText("")
            text=text*text2
            self.label.setText(str(text))
            operator=""

        if operator=="/":
            text2=self.label.text()
            text2=float(text2)
            self.label.setText("")
            text=text/text2
            self.label.setText(str(text))
            operator=""
        
        if operator=="**":
            text2=self.label.text()
            text2=float(text2)
            self.label.setText("")
            text=math.pow(text,text2) 
            self.label.setText(str(text))
            operator=""

        if operator=="sin":

            if text=="":
                text2=self.label.text()
                text2=float(text2)
                self.label.setText("")
                text2=math.sin(math.radians(text2))
                self.label.setText(str(text2))
                

        if operator=="cos":
                
            if text=="":
                text2=self.label.text()
                text2=float(text2)
                self.label.setText("")
                text2=math.cos(math.radians(text2))
                self.label.setText(str(text2))

        if operator=="tan":
            if text=="":
                text2=self.label.text()
                text2=float(text2)
                self.label.setText("")
                text2=math.tan(math.radians(text2))
                self.label.setText(str(text2))

        if text3 !="" and op2 !="":
            c=1
            operator=op2
            text=text3
            text3=""
            op2=""
            
        if c==1:
            c=0
            self.method_answer()
            
        
            text=self.label.text()
            text=float(text)
            operator=""
            
            
        
        
        

        
        


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_clear.setText(_translate("MainWindow", "Clear"))
        self.label.setText(_translate("MainWindow",""))
        self.pushButton_del.setText(_translate("MainWindow", "Delete"))
        self.pushButton_dot.setText(_translate("MainWindow", "."))
        self.pushButton_dot.setShortcut(_translate("MainWindow", "."))
        self.pushButton_zero.setText(_translate("MainWindow", "0"))
        self.pushButton_zero.setShortcut(_translate("MainWindow", "0"))
        self.pushButton_answer.setText(_translate("MainWindow", "="))
        self.pushButton_answer.setShortcut(_translate("MainWindow", "="))
        self.pushButton_pluse.setText(_translate("MainWindow", "+"))
        self.pushButton_pluse.setShortcut(_translate("MainWindow", "+"))
        self.pushButton_devide.setText(_translate("MainWindow", "/"))
        self.pushButton_devide.setShortcut(_translate("MainWindow", "/"))
        self.pushButton_minus.setText(_translate("MainWindow", "-"))
        self.pushButton_minus.setShortcut(_translate("MainWindow", "-"))
        self.pushButton_multiple.setText(_translate("MainWindow", "*"))
        self.pushButton_multiple.setShortcut(_translate("MainWindow", "*"))
        self.pushButton_power.setText(_translate("MainWindow", "^"))
        self.pushButton_power.setShortcut(_translate("MainWindow", "^"))
        self.pushButton_sin.setText(_translate("MainWindow", "Sin"))
        self.pushButton_cos.setText(_translate("MainWindow", "Cos"))
        self.pushButton_tan.setText(_translate("MainWindow", "Tan"))
        self.pushButton.setText(_translate("MainWindow", "1"))
        self.pushButton.setShortcut(_translate("MainWindow", "1"))
        self.pushButton_2.setText(_translate("MainWindow", "2"))
        self.pushButton_2.setShortcut(_translate("MainWindow", "2"))
        self.pushButton_3.setText(_translate("MainWindow", "3"))
        self.pushButton_3.setShortcut(_translate("MainWindow", "3"))
        self.pushButton_4.setText(_translate("MainWindow", "4"))
        self.pushButton_4.setShortcut(_translate("MainWindow", "4"))
        self.pushButton_5.setText(_translate("MainWindow", "5"))
        self.pushButton_5.setShortcut(_translate("MainWindow", "5, 5"))
        self.pushButton_6.setText(_translate("MainWindow", "6"))
        self.pushButton_6.setShortcut(_translate("MainWindow", "6"))
        self.pushButton_7.setText(_translate("MainWindow", "7"))
        self.pushButton_7.setShortcut(_translate("MainWindow", "7"))
        self.pushButton_8.setText(_translate("MainWindow", "8"))
        self.pushButton_8.setShortcut(_translate("MainWindow", "8"))
        self.pushButton_9.setText(_translate("MainWindow", "9"))
        self.pushButton_9.setShortcut(_translate("MainWindow", "9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
